### ISSUE TITLE
Couleur pour thème sombre

### ISSUE THREAD

**Issue by ghost** [MineWeb/Plugin-Changelogs#13]
Possibilité de changer la couleur de l'écriture pour la date etc ? Car sur un thème à fond sombre, l'écriture blanche ne se voit pas (car fond blanc).

**Comment by valentinhttr** [comment]
Salut @TonyoBlaster,

Je t'invite à créer une adaptation du plugin pour ton thème en particulier.

Merci de l'utiliser en tout cas !

**Comment by ByFow** [comment]
Tu peux modifier le code du plugin pour effectuer ta modification ;)

**Comment by valentinhttr** [comment]
Hello. Sans réponse, je pars du principe que le souci est réglé. Je ferme donc l'issue.

N'hésite pas à demander de l'aide sur le discord de Mineweb si tu rencontres toujours des difficultés.
