### ISSUE TITLE
changer le nom du dossier 

### ISSUE THREAD

**Issue by sadoj-kuro** [MineWeb/Plugin-Changelogs#2]
Le nom du dossier est pas bon au lieux de Changelog faut mettre ChangeLog sinon pas accessible par le panel admin

**Comment by Eywek** [comment]
Modifier le nom du plugin dans les routes devrait être plus simple https://github.com/MineWeb/Plugin-Changelog/blob/master/Config/routes.php

**Comment by sadoj-kuro** [comment]
effectivement
