### ISSUE TITLE
erreur interne pour accéder à /admin/changelog

### ISSUE THREAD

**Issue by ImLacy** [MineWeb/Plugin-Changelogs#5]
Bonjour,
Quand je veux accéder à /admin/ChangeLog ça me met que la page est introuvable, j'ai donc essayé /admin/changelog et ça me met un erreur interne et j’obtiens ceci dans mon error.log (De mineweb)
https://hastebin.com/imetucayit.pas

Savez-vous comment régler ce problème ?
PS: j'ai essayé de vider le cache sans succès

**Comment by valentinhttr** [comment]
Salut @AzhukOffi,

En effet, le nom du plugin n'étant plus le même sur Github, une PR a été soumise pour modifier les routes : https://github.com/MineWeb/Plugin-Changelog/pull/4

Je viens de l'accepter, essaie de supprimer le plugin, de le réinstaller (télécharge-le à nouveau) et vide ton cache encore une fois stp.

Bonne soirée.

**Comment by ArthieuCYD** [comment]
Bonjour, j'ai le même problème et après avoir fait les modifications et vider le cache encore une fois, il y a une erreur 500.

Bonne journée

**Comment by ImLacy** [comment]
ça marche parfaitement merci
